#pragma once

#include <cstdint>
namespace srl {

    ///Declaration of type which holds hash of schema
    /**
        The hash is calculated from content generated by serialize and deserialize function
        You can check, that item has valid schema just by comparing SchemaHash with expected value        
    */
    using SchemaHash = std::uint64_t;

}