#pragma once

#include "quarkbot/abstract/orderdata.hpp"
#include "quarkbot/stream/auction.hpp"
#include "quarkbot/stream/quote.hpp"
#include "quarkbot/stream/trade.hpp"
#include <chrono>
#include <functional>
#include <string>
#include <type_traits>

namespace quarkbot {

class IExchange;
class IAccount;

///Custom backtest event that can be executed on specified simulation time
using CustomBacktestEvent = std::function<void(std::string_view)>;
///Custom backtest event that can be executed on specified simulation time and has access to the simulated exchange
using CustomBacktestEventOnExchange = std::function<void(std::string_view, IExchange *)>;
///Custom backtest event that can be executed on specified simulation time and has access to the simulated account
using CustomBacktestEventOnAccount = std::function<void(std::string_view, IAccount *)>;

///Backtest event that can be generated by the backtest data source
struct BacktestEvent {
    ///Symbol of the instrument for which the event is generated (passed to the custom event as a parameter)
    std::string symbol;
    ///Time of the event
    std::chrono::system_clock::time_point time;
    ///Data of the event, can be a trade, quote, auction or a custom event
    std::variant<CustomBacktestEvent, CustomBacktestEventOnExchange, CustomBacktestEventOnAccount, Trade, Quote, Auction> data;
};

template<typename T>
concept BacktestDataSourceType = std::is_invocable_r_v<bool, T, BacktestEvent &>;

///Backtest data source is a function that provides backtest events. It is called repeatedly until it returns false.
using BacktestDataSource = std::move_only_function<bool(BacktestEvent &ev)>;

///Initial wallet state for the backtest environment, a list of currency and their amounts
using WalletInitItem = std::pair<std::string, Decimal>;

///Report sink is a function that is called for each order update, it can be used to generate reports
using ReportSink = std::function<void(const POrderAData &, const OrderInternalData::Update &)>;


} // namespace quarkbot
