[simulator]

    [replay]
        r1:  #declaration of replay file
            file=/home/ondra/Stažené/minute_bybit_f_BTCUSD.csv
            speed=1     #multiply each timestamp by this number
            offset=0    #add number to timestamp (seconds)
            
            [mmbot]     #specify this section, if mmbot format source 
            symbol=BTCUSD #manifested symbol (mandatory)
            seed=123    #random seed  (0)
            events_per_minute=10  #average events per minute (10) 
            spread_percent = 0.1  #random generated spread in percent (0.1)
            min_volume= 0.001     #min reported volume (1)
            max_volume= 5         #max reported volume (100)
            
            
    [options]
    
    # specify simulated latency to place/cancel order in seconds
    # (you can use decimal value for subsecond latency)                
    order_latency=0.1


[accounts]
    acc1:

        [query]             # mandatory - compatibility with main configuration
        balance=1000  #account balance
        currency=USD  #account currency (string)
        fees = 0.001  #fees in %    

[instruments]
    Bitcoin:
    
        [query]             # mandatory - compatibility with main configuration
        symbol=BTCUSD       # symbol name in replay file(s)
        type=spot
        tick_size=0.01
        lot_size=0.0001
        lot_multiplier=1
        min_size=0.0001,
        min_volume=0,
        quanto_factor=1
        initial_margin=1
        maintenance_margin=1
        tradable=true
        can_short=true
        currency=USD

[strategies]
    main:
        name=Example                  # name of the strategy in the module
        instruments= Bitcoin          # list of instruments
        accounts= acc1                # list of accounts

        [configuration]               # configuration of the strategy
        key=value

