#pragma once

#include "quarkbot/memory.hpp"
#include "types.hpp"
#include "round_policy.hpp"
#include <list>


namespace quarkbot {

template<typename T>
using FastList = std::list<T, LockFreeFramePool::Allocator<T> >;


enum class OrderType : char{
    ///alert - works as stop, stop_price is mandatory, filled when triggered, no fill generated
    /** alerts can be emulated if not supported on exchange */
    alert,
    ///market order - amount is mandarory
    market,
    ///limit order - amount and limit_price are mandatory
    limit,
    ///limit post only - order is reject when it would fill immediately - amount and limit_price are mandatory
    limit_post_only,
    ///stop order - amount and stop_price are mandatory
    stop,
    ///stop limit order - amount, stop_price and limit_price are mandatory
    stoplimit,
    ///pair of orders - one order is limit, second is stop. When one is filled, the other is canceled
    oco
};

enum class TimeInForce : char {
    ///Good until canceled
    gtc,
    ///Day only, canceled at close
    day,
    ///immediate or cancel
    ioc,
    ///fill or kill 
    fok,
    ///at close
    atc,
    ///at open
    ato,    
    ///at crossing
    crossing    
};

inline constexpr bool is_limit_order(OrderType type) {
    return type == OrderType::limit
        || type == OrderType::limit_post_only
        || type == OrderType::oco
        || type == OrderType::stoplimit;
}


inline constexpr bool is_stop_order(OrderType type) {
    return type == OrderType::stop
        || type == OrderType::stoplimit
        || type == OrderType::alert
        || type == OrderType::oco;
}

inline constexpr bool is_auction_order(TimeInForce type) {
    return type == TimeInForce::atc || type == TimeInForce::ato || type == TimeInForce::crossing;
}

inline constexpr bool is_valid_auction_order(OrderType type) {
    return type == OrderType::market || type == OrderType::limit;
}



template<typename NumberType>
struct OrderParametersGen {
    ///order name 
    /**
    Custom order name, can be any string, including empty. This name appears on fills generated by this order, so you can
    later use name for analysis
     */
    std::string label;
    ///order side
    Side side;
    ///order type
    OrderType type;
    ///amount (positive number)
    NumberType quantity; //mandatory
    ///limit price (for limit orders)
    NumberType limit_price = {};
    ///stop price (for stop orders)
    NumberType stop_price = {};
    ///time in force
    TimeInForce time_in_force = TimeInForce::gtc;
    ///max leverage (0 = disabled)
    double leverage = 0;
    
    ///reduce or close position
    bool reduce_only = false;
    ///create or increase to hedge side - can open reverse position if supported on exchange
    bool hedge = false;
    ///Enforce that limit, stop or alert is triggered on local side, not on exchange, even if exchange supports it.    
    /**
        - limit - converted to trigger, which is placed to the exchange when instrument price reaches the limit price 
        - stop - converted to trigger placing market order
        - stoplimit - converted to trigger placing limit order
        - alert - reported as filled when prices is triggered

        @note some of settings are not supported, for example time_in_force is applied to final order, until order is
        triggered, GTC is in effect. Also such an order cannot be replaced when it is already triggered. It is also
        possible, that some values of the order will not be accessible, for example the order id. The order cannot be
        stored in storage - however when the trigger is activated, created order will be stored in the storage. 

    */
    bool local_trigger = false;
    ///Specifies that order must outlive its local instance
    /**
        If this field is false, the order will be automatically canceled when the corresponding instance of the order is dropped.
        Set this field to true to keep order alive. This can be useful for orders required to be completed, for example
        emergency orders to close current position at all costs.
    */
    bool keep_alive = false;
    ///sets execution reason for given order 
    /**
      Allows to override execution reason for strategy orders. 
     */
    ExecutionReason reason_override = ExecutionReason::strategy_order;

    auto fields(this auto &self) {
        return std::tie(self.label,
                        self.side,
                        self.type,
                        self.quantity,
                        self.limit_price,
                        self.stop_price,
                        self.time_in_force,
                        self.leverage,
                        self.reduce_only,
                        self.hedge,
                        self.local_trigger,
                        self.keep_alive,
                        self.reason_override);
    }
};

using OrderParameters = OrderParametersGen<Decimal>;
using OrderRequest = OrderParametersGen<TargetValue>;



enum class OrderStatus : uint8_t {
    ///order status is unknown - this is default
    unknown = 0,
    ///order sent, not confirmed yet
    sent,
    ///order is awaiting trigger, this state is used for locally managed triggers, should not be emited by exchanges. 
    pending_trigger,
    ///order is active, open, waiting in orderbook, there can be partial fills (see fills)
    open,    
    ///order is done, filled complete
    filled,
    ///order is done, has been canceled
    canceled,
    ///order is done, has been rejected
    rejected,    
    ///order is done, has been replaced by other order
    replaced,
    ///order has been recently restored from storage and exchange adapter is synchronizing its state
    restored,
    ///order is done, informations about the order are lost - this can happen as resolution of restored state. (order is no longer found in history)
    lost
};

enum class OrderRejectionReason : uint8_t{
    //no reason given
    none,
    //instrument not tradable
    not_tradable,
    //order is too large
    too_large,
    //order is too small
    too_small,    
    //no funds
    insufficient_funds,
    //invalid parameters
    invalid_params,
    //order cannot be replaced (incompatible settings)
    invalid_replace,
    //order cannot be replaced, because old order was not found (is probably done)
    order_not_found,
    //price is not allowed range
    price_range,
    //post only order would take liquidity
    post_only_taker,
    //minimum order volume
    min_volume,
    //too late for this order (for example, auction order was too late, auction already resolved)
    too_late,
    //exchange is overloaded
    overloaded,
    //exchange rate limit implemented
    rate_limited,
    //risk limit reached
    too_risky,
    //denied by exchange 
    permission_denied,
    //order configuration is not supported by this exchange
    unsupported,
    //order was not posted to exchange - connection stalled
    timeout,
    //order expired before delivered
    expired,
    //reduce order doesn't reduce position
    reduce_doesnt_reduce,
    //order rejected because too large slippage
    slippage,
    //rejected because exchange as an internal issue
    exchange_issue,
    //internal error  (probably adapter error, connection, etc)
    internal_error,
    //other reason (textural),
    other
};

inline constexpr bool is_done_status(OrderStatus status) {
    return status == OrderStatus::filled ||
           status == OrderStatus::canceled ||
           status == OrderStatus::rejected ||
           status == OrderStatus::replaced ||
           status == OrderStatus::lost ;
}

struct OrderRejectionWithText {
    OrderRejectionReason reason;
    std::string text;
};

struct OrderOpenStatus {
    std::string id;
    RecordKey key;
};


struct OrderReport {
    //can contain rejection message
    std::string rejection_message = {};
    //the vector contains unprocessed fills
    FastList<Fill> fills = {};
    //total filled amount (as reported from adapter)
    Decimal filled = 0;
    //total turnover (quantity * price accumulated)
    Decimal turnover = 0;
    ///is set true if status changed while new report was generated
    bool status_changed = false;
    ///current status of the order
    OrderStatus status = OrderStatus::unknown;
    ///if order is rejected, contains rejection reason
    OrderRejectionReason rejection_reason = OrderRejectionReason::none;
    ///contains internal order's id  - depends on adapter/exchange - note content is valid until order instance is destroyed
    std::string_view id;

    //calc average fill price
    Decimal calc_avg_fill_price() const {
        if (filled) return turnover/filled;
        return 0;
    }

    //report contains done status
    bool is_done() const {
        return is_done_status(status);
    }

};



}