#pragma once

#include "quarkbot/timestamp.hpp"
#include <optional>
namespace quarkbot {




class IBacktestDebugger {
public:


    enum class EventType {        
        ///event generated by data set - debugger is called after the event is processed
        data,
        ///event generated by scheduler (timer) - debugger after event is processed
        scheduler 
    };


    virtual ~IBacktestDebugger() = default;

    // backtest face

    /** called by backtest cycle for everytime the time changes
        @param tp current simulation time
        @param data_event true, if current 
        @retval true continue in execution
        @retval false stop execution (exit)
    */
    virtual bool on_debugger_event(const Timestamp &tp, EventType type) = 0;
    

    virtual void on_exit() =0;

    enum class RunStatus {
        ///backtest is paused
        paused,
        ///backtest is running
        running,
        ///backtest is done.
        done
    };

    enum class TraceMode {
        ///trace is disabled, 
        disabled,
        ///execution stops on next event
        step,
        ///execution stops on next data event
        step_data_event,
        ///execution stops on breakpoint (specified by the time)
        breakpoint        
    };


    struct Status {
        ///Run status
        RunStatus run_status;  
        ///current event type (useful only when stopped)
        EventType event;
        ///current time
        Timestamp time;
        ///current trace_mode
        TraceMode trace_mode;
        ///current breakpoint, for trace_mode == breakpoint, otherwise ignored
        Timestamp breakpoint;
    };

    ///retrieve simulator status. This function is MT safe
    virtual Status get_status() const = 0;

    ///set running status. Set true to run, set false to pause (this function in MT safe)
    /**
        @param running true by setting true, the debugger continues to run                
     */
    virtual void set_running(bool running) = 0;


    ///Sets trace mode
    /**
        @param mode new trace mode. If you set mode breakpoint, it reuses previously set breakpoint value. It is better to use set_breakpoint

        @note function doesn't change run state, You need to call set_running(true) to continue.

        Function is MT safe


    */
    virtual void set_trace_mode(TraceMode mode) = 0;

    ///set breakpoint on given time
    /**
        @param tp new breakpoint time

        @note breakpoint causes stop when time reaches breakpoint or later. Setting breakpoint to history, backtest executes one event and stops
        
        @note you must clear breakpoint manually to continue running

        @note function is MT safe
    */
    virtual void set_breakpoint(Timestamp tp) = 0;


    ///quit debugger, terminate the run. The status changes to done.
    /**
        Exits regardless on state of replay
        Strategy is signaled about stop operation
    */
    virtual void quit() = 0;
};

}