#pragma once

#include "quarkbot/abstract/backtest_data_source.hpp"
#include <chrono>
#include <filesystem>
#include <fstream>
#include <istream>
#include <optional>

namespace quarkbot {


    ///Example of a backtest data source that reads minute data from a file or stream.
    /** The file must contain one number per line, which is the price of the instrument at that minute. 
        The first line is the price at the start time, the second line is the price at start time + 1 minute, etc.
        There are no timestamps in the file, the timestamps are generated by the backtest environment based on the start time and the number of lines read.
        The backtest data source generates a Quote event for each minute, with the bid and ask prices being the minimum and maximum of the current and previous price, and a Trade event with the average price of the current and previous price. The Trade event is generated 30 seconds after the Quote event

        Intended for testing, or for slow strategies that do not require high frequency data.
        Very easy to generate and use.
    */
    class MinuteDataSource  {
    public:

        bool operator()(BacktestEvent &ev);
        MinuteDataSource(std::string instrument, std::filesystem::path path, std::chrono::system_clock::time_point start_time);
        MinuteDataSource(std::string instrument, std::istream &stream, std::chrono::system_clock::time_point start_time);


    protected:
        Decimal _prev_price;
        std::ifstream _ifstream;
        std::istream &_stream;
        std::string _instrument;
        std::chrono::system_clock::time_point _tp;
        std::optional<Decimal> _price;
        
        std::optional<Decimal> load_number();
    };

}